#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_MARIO2 30

#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_BRICK_PLATFORM 6
#define OBJECT_TYPE_LARGE_BUSH_1 100
#define OBJECT_TYPE_LARGE_BUSH_2 110
#define OBJECT_TYPE_CLOUD_1 120
#define OBJECT_TYPE_CLOUD_2 130
#define OBJECT_TYPE_SMALL_BUSH 140
#define OBJECT_TYPE_BOX_1_SINGLE_LONG_PINK 150
#define OBJECT_TYPE_BOX_1_SINGLE_SHORT_PINK 152
#define OBJECT_TYPE_BOX_1_SINGLE_BLUE 154
#define OBJECT_TYPE_BOX_1_SINGLE_GREEN 156
#define OBJECT_TYPE_BOX_2_DOUBLE_SHORT 160
#define OBJECT_TYPE_BOX_2_DOUBLE_TALL 162
#define OBJECT_TYPE_BOX_3_TRIPLE 170

#define OBJECT_TYPE_PORTAL	50


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#pragma region MARIO2
#define ID_SPRITE_MARIO2 70000
#define ID_SPRITE_MARIO2_BIG (ID_SPRITE_MARIO2 + 1000)
#define ID_SPRITE_MARIO2_BIG_IDLE (ID_SPRITE_MARIO2_BIG + 100)
#define ID_SPRITE_MARIO2_BIG_IDLE_LEFT (ID_SPRITE_MARIO2_BIG_IDLE + 10)
#define ID_SPRITE_MARIO2_BIG_IDLE_RIGHT (ID_SPRITE_MARIO2_BIG_IDLE + 20)

#define ID_SPRITE_MARIO2_BIG_WALKING (ID_SPRITE_MARIO2_BIG + 200)
#define ID_SPRITE_MARIO2_BIG_WALKING_LEFT (ID_SPRITE_MARIO2_BIG_WALKING + 10)
#define ID_SPRITE_MARIO2_BIG_WALKING_RIGHT (ID_SPRITE_MARIO2_BIG_WALKING + 20)
#define ID_SPRITE_MARIO2_BIG_RUNNING (ID_SPRITE_MARIO2_BIG + 300)
#define ID_SPRITE_MARIO2_BIG_RUNNING_LEFT (ID_SPRITE_MARIO2_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO2_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO2_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO2_BIG_JUMP (ID_SPRITE_MARIO2_BIG + 400)
#define ID_SPRITE_MARIO2_BIG_JUMP_WALK (ID_SPRITE_MARIO2_BIG_JUMP + 10)
#define ID_SPRITE_MARIO2_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO2_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO2_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO2_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO2_BIG_JUMP_RUN (ID_SPRITE_MARIO2_BIG_JUMP + 20)
#define ID_SPRITE_MARIO2_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO2_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO2_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO2_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO2_BIG_SIT (ID_SPRITE_MARIO2_BIG + 500)
#define ID_SPRITE_MARIO2_BIG_SIT_LEFT (ID_SPRITE_MARIO2_BIG_SIT + 10)
#define ID_SPRITE_MARIO2_BIG_SIT_RIGHT (ID_SPRITE_MARIO2_BIG_SIT + 20)
#define ID_SPRITE_MARIO2_BIG_BRACE (ID_SPRITE_MARIO2_BIG + 600)
#define ID_SPRITE_MARIO2_BIG_BRACE_LEFT (ID_SPRITE_MARIO2_BIG_BRACE + 10)
#define ID_SPRITE_MARIO2_BIG_BRACE_RIGHT (ID_SPRITE_MARIO2_BIG_BRACE + 20)
#define ID_SPRITE_MARIO2_DIE (ID_SPRITE_MARIO2 + 3000)
#define ID_SPRITE_MARIO2_SMALL (ID_SPRITE_MARIO2 + 2000)
#define ID_SPRITE_MARIO2_SMALL_IDLE (ID_SPRITE_MARIO2_SMALL + 100)
#define ID_SPRITE_MARIO2_SMALL_IDLE_LEFT (ID_SPRITE_MARIO2_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO2_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO2_SMALL_IDLE + 20)
#define ID_SPRITE_MARIO2_SMALL_WALKING (ID_SPRITE_MARIO2_SMALL + 200)
#define ID_SPRITE_MARIO2_SMALL_WALKING_LEFT (ID_SPRITE_MARIO2_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO2_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO2_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO2_SMALL_RUNNING (ID_SPRITE_MARIO2_SMALL + 300)
#define ID_SPRITE_MARIO2_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO2_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO2_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO2_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO2_SMALL_JUMP (ID_SPRITE_MARIO2_SMALL + 400)
#define ID_SPRITE_MARIO2_SMALL_JUMP_WALK (ID_SPRITE_MARIO2_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO2_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO2_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO2_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO2_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO2_SMALL_JUMP_RUN (ID_SPRITE_MARIO2_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO2_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO2_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO2_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO2_SMALL_JUMP_RUN + 6)
#define ID_SPRITE_MARIO2_SMALL_SIT (ID_SPRITE_MARIO2_SMALL + 500)
#define ID_SPRITE_MARIO2_SMALL_SIT_LEFT (ID_SPRITE_MARIO2_SMALL_SIT + 10)
#define ID_SPRITE_MARIO2_SMALL_SIT_RIGHT (ID_SPRITE_MARIO2_SMALL_SIT + 20)
#define ID_SPRITE_MARIO2_SMALL_BRACE (ID_SPRITE_MARIO2_SMALL + 500)
#define ID_SPRITE_MARIO2_SMALL_BRACE_LEFT (ID_SPRITE_MARIO2_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO2_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO2_SMALL_BRACE + 20)
#pragma endregion



#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000 //This only use to define ID_SPRITE_CLOUD_BEGIN, ID_SPRITE_CLOUD_MIDDLE, ID_SPRITE_CLOUD_END
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

#define ID_SPRITE_BRICK_PLATFORM 60000
#define ID_SPRITE_BRICK_PLATFORM_BEGIN (ID_SPRITE_BRICK_PLATFORM + 1000)
#define ID_SPRITE_BRICK_PLATFORM_MIDDLE (ID_SPRITE_BRICK_PLATFORM + 2000)
#define ID_SPRITE_BRICK_PLATFORM_END (ID_SPRITE_BRICK_PLATFORM + 3000)

#define ID_SPRITE_LARGE_BUSH_1 (OBJECT_TYPE_LARGE_BUSH_1 + 1)
#define ID_SPRITE_LARGE_BUSH_2 (OBJECT_TYPE_LARGE_BUSH_2 + 1)

#define ID_SPRITE_CLOUD_1 (OBJECT_TYPE_CLOUD_1 + 1)
#define ID_SPRITE_CLOUD_2 (OBJECT_TYPE_CLOUD_2 + 1)
#define ID_SPRITE_SMALL_BUSH (OBJECT_TYPE_SMALL_BUSH + 1)

#define ID_SPRITE_BOX_1_SINGLE_LONG_PINK (OBJECT_TYPE_BOX_1_SINGLE_LONG_PINK + 1)
#define ID_SPRITE_BOX_1_SINGLE_SHORT_PINK (OBJECT_TYPE_BOX_1_SINGLE_SHORT_PINK + 1)
#define ID_SPRITE_BOX_1_SINGLE_BLUE (OBJECT_TYPE_BOX_1_SINGLE_BLUE + 1)
#define ID_SPRITE_BOX_1_SINGLE_GREEN (OBJECT_TYPE_BOX_1_SINGLE_GREEN + 1)
#define ID_SPRITE_BOX_2_DOUBLE_SHORT (OBJECT_TYPE_BOX_2_DOUBLE_SHORT + 1)
#define ID_SPRITE_BOX_2_DOUBLE_TALL (OBJECT_TYPE_BOX_2_DOUBLE_TALL + 1)
#define ID_SPRITE_BOX_3_TRIPLE (OBJECT_TYPE_BOX_3_TRIPLE + 1)
